from no import *
from aresta import *
from AEstrela import *

arad = No("Arad", 366)
zerid = No("Zerid", 374)
sibiu = No("Sibiu", 253)
timisoara = No("Timisoara", 329)
mehadia = No("Mehadia", 241)
neamt = No("Neamt", 234)
oradea = No("Oradea", 380)
pitesti = No("Pitesti", 100)
rimnicu_vilcea = No("Rimnicu Vilcea", 193)
fagaras = No("Fagaras", 176)
giurgiu = No("Giurgiu", 77)
hirsova = No("Hirsova", 151)
urziceni = No("Urziceni", 80)
iasi = No("Iasi", 226)
vaslui = No("Vaslui", 199)
lugoj = No("Lugoj", 244)
zerind = No("Zerind", 374)
dobreta = No("Dobreta", 242)
craiova = No("Craiova", 160)
bucharest = No("Bucharest", 0)
eforie = No("Eforie", 161)

arad.set_adjasente([aresta(75,zerid), aresta(140, sibiu), aresta(118,timisoara)])
zerid.set_adjasente([aresta(75,arad), aresta(71, oradea)])
oradea.set_adjasente([aresta(71, zerind), aresta(151, sibiu)])
sibiu.set_adjasente([aresta(151, oradea),aresta(140, arad), aresta(99, fagaras), aresta(80, rimnicu_vilcea)])
timisoara.set_adjasente([aresta(118, arad),aresta(111,lugoj)])
lugoj.set_adjasente([aresta(111,timisoara), aresta(70,mehadia)])
mehadia.set_adjasente([aresta(70,lugoj), aresta(75, dobreta)])
dobreta.set_adjasente([aresta(75, mehadia), aresta(120, craiova)])
craiova.set_adjasente([aresta(120, dobreta), aresta(138, pitesti), aresta(146, rimnicu_vilcea)])
rimnicu_vilcea.set_adjasente([aresta(146, craiova), aresta(80, sibiu), aresta(97, pitesti)])
pitesti.set_adjasente([aresta(138, craiova), aresta(97, rimnicu_vilcea), aresta(101, bucharest)])
fagaras.set_adjasente([aresta(99,sibiu), aresta(211,bucharest)])
bucharest.set_adjasente([aresta(90, giurgiu), aresta(101, pitesti), aresta(211, fagaras), aresta(85, urziceni)])
urziceni.set_adjasente([aresta(85, bucharest), aresta(142, vaslui), aresta(98, hirsova)])
hirsova.set_adjasente([aresta(98, urziceni), aresta(86,eforie)])
eforie.set_adjasente([aresta(86, hirsova)])
vaslui.set_adjasente([aresta(142, urziceni), aresta(92, iasi)])
iasi.set_adjasente([aresta(92, vaslui), aresta(87, neamt)])
neamt.set_adjasente([aresta(87, iasi)])

a_estrela = AEstrela()
a_estrela.busca_AEstrela(lugoj, bucharest)
print(a_estrela.percorrer_caminho(bucharest))